// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSqTYq0LlvjQHvXHxvblBcPdDbl0BkvJY',
    appId: '1:220808228715:web:95678ac59accc51251262e',
    messagingSenderId: '220808228715',
    projectId: 'humanacare-bc359',
    authDomain: 'humanacare-bc359.firebaseapp.com',
    storageBucket: 'humanacare-bc359.firebasestorage.app',
    measurementId: 'G-2L5GNNTTVG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdEG9ObLqwoN2GbkSFHkvlJh9gFEAECVs',
    appId: '1:220808228715:android:4f791a2ec2baebc551262e',
    messagingSenderId: '220808228715',
    projectId: 'humanacare-bc359',
    storageBucket: 'humanacare-bc359.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcvEoNyxF-LdpyxGYVtURVIwGwC0nt1_4',
    appId: '1:220808228715:ios:cc2f246e934c330051262e',
    messagingSenderId: '220808228715',
    projectId: 'humanacare-bc359',
    storageBucket: 'humanacare-bc359.firebasestorage.app',
    iosBundleId: 'com.example.humanacarePaciente',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcvEoNyxF-LdpyxGYVtURVIwGwC0nt1_4',
    appId: '1:220808228715:ios:cc2f246e934c330051262e',
    messagingSenderId: '220808228715',
    projectId: 'humanacare-bc359',
    storageBucket: 'humanacare-bc359.firebasestorage.app',
    iosBundleId: 'com.example.humanacarePaciente',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSqTYq0LlvjQHvXHxvblBcPdDbl0BkvJY',
    appId: '1:220808228715:web:f9ea11f56abb74ec51262e',
    messagingSenderId: '220808228715',
    projectId: 'humanacare-bc359',
    authDomain: 'humanacare-bc359.firebaseapp.com',
    storageBucket: 'humanacare-bc359.firebasestorage.app',
    measurementId: 'G-CJPL4LLJ7T',
  );
}
